// <auto-generated />
using System;
using Aspire.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aspire.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Aspire.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PostTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Support")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("PostStatusId");

                    b.HasIndex("PostTypeId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Aspire.Models.PostStatus", b =>
                {
                    b.Property<int>("PostStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostStatusId"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptiion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostStatusId");

                    b.ToTable("PostStatuses");

                    b.HasData(
                        new
                        {
                            PostStatusId = 1,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7967),
                            Descriptiion = "This status shows the post is open to use with Auther's permission.",
                            Name = "Open"
                        },
                        new
                        {
                            PostStatusId = 2,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7970),
                            Descriptiion = "This status shows that the post is adopted and under cunstruction.",
                            Name = "In Progress"
                        },
                        new
                        {
                            PostStatusId = 3,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7973),
                            Descriptiion = "This status shows that the post is completed but still open to adopt with auther's permission.",
                            Name = "Completed"
                        },
                        new
                        {
                            PostStatusId = 4,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7976),
                            Descriptiion = "This status shows that the post should not be displayed to anyone.",
                            Name = "Private"
                        },
                        new
                        {
                            PostStatusId = 5,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7978),
                            Descriptiion = "This post is forcefully removed from the post library.",
                            Name = "Blocked"
                        });
                });

            modelBuilder.Entity("Aspire.Models.PostType", b =>
                {
                    b.Property<int>("PostTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostTypeId"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptiion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostTypeId");

                    b.ToTable("PostTypes");

                    b.HasData(
                        new
                        {
                            PostTypeId = 1,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7818),
                            Descriptiion = "The post that use this type is a new and has to be builded from the scratch.",
                            Name = "New"
                        },
                        new
                        {
                            PostTypeId = 2,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7822),
                            Descriptiion = "The post that use this type is something already exists and has to be updated it could be anything including adding a new feature.",
                            Name = "Updation"
                        },
                        new
                        {
                            PostTypeId = 3,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7824),
                            Descriptiion = "The post that use this type is something that already exists and Buged that need to be Fixed.",
                            Name = "Bug"
                        },
                        new
                        {
                            PostTypeId = 4,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7827),
                            Descriptiion = "The post that use this type is Something that only required Design.",
                            Name = "Design"
                        },
                        new
                        {
                            PostTypeId = 5,
                            CreatedOn = new DateTime(2022, 3, 2, 7, 55, 15, 237, DateTimeKind.Local).AddTicks(7830),
                            Descriptiion = "The post that use this type is Something that is designed and need cunstruction",
                            Name = "Cunstruction"
                        });
                });

            modelBuilder.Entity("Aspire.Models.Post", b =>
                {
                    b.HasOne("Aspire.Models.PostStatus", "PostStatus")
                        .WithMany()
                        .HasForeignKey("PostStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aspire.Models.PostType", "PostType")
                        .WithMany()
                        .HasForeignKey("PostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostStatus");

                    b.Navigation("PostType");
                });
#pragma warning restore 612, 618
        }
    }
}
